apiVersion: v1
kind: Pod
metadata:
  name: pgsc-calc
spec:
  restartPolicy: Never
  containers:
    - name: nextflow-driver
      image: docker.io/nextflow/nextflow:21.10.6
      env:
        - name: NXF_EXECUTOR
          value: "k8s"
        - name: NXF_HOME
          value: "/workspace/nextflow"
      command: ["nextflow"]
      args: ["run", "pgscatalog/pgsc_calc", "-r", "master", "-profile", "test,k8s", "--input", "/workspace/data/samplesheet.csv", "--scorefile", "/workspace/data/PGS001229_22.txt", "-w", "/workspace/work"]
      volumeMounts:
        - name: vol-1
          mountPath: /workspace
      resources:
        requests:
          cpu: 2
          memory: 2G
        limits:
          cpu: 2
          memory: 3G
  volumes:
    - name: vol-1
      persistentVolumeClaim:
        claimName: nfsclaim

