name: Run ancestry test with mamba profile

on:
  workflow_call:
    inputs:
      ancestry-cache-key:
        type: string
        required: true
  
jobs:
  test_mamba_ancestry:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "ANCESTRY_REF_DIR=$RUNNER_TEMP" >> $GITHUB_ENV
          echo "ANCESTRY_TARGET_DIR=$RUNNER_TEMP" >> $GITHUB_ENV

      - name: Restore reference data
        uses: actions/cache/restore@v3
        with:
          path: |
            ${{ env.ANCESTRY_TARGET_DIR }}/GRCh38_HAPNEST_TARGET_ALL.pgen
            ${{ env.ANCESTRY_TARGET_DIR }}/GRCh38_HAPNEST_TARGET_ALL.psam
            ${{ env.ANCESTRY_TARGET_DIR }}/GRCh38_HAPNEST_TARGET_ALL.pvar.zst
            ${{ env.ANCESTRY_REF_DIR }}/GRCh38_HAPNEST_reference.tar.zst
          key: ${{ inputs.ancestry-cache-key }}
          fail-on-cache-miss: true
  
      - uses: conda-incubator/setup-miniconda@v2
        with:  
          channels: conda-forge,bioconda,defaults
          miniforge-variant: Mambaforge
          miniforge-version: latest
          python-version: "3.10"
          
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: install nxf
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Set up test requirements
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - run: pip install -r ${{ github.workspace }}/tests/requirements.txt

      - name: Run ancestry test
        run: TMPDIR=~ PROFILE=mamba pytest --kwdof --symlink --git-aware --wt 2 --tag "ancestry" --ignore tests/bin

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: logs-conda-ancestry
          path: |
            /home/runner/pytest_workflow_*/*/.nextflow.log
            /home/runner/pytest_workflow_*/*/log.out
            /home/runner/pytest_workflow_*/*/log.err
            /home/runner/pytest_workflow_*/*/output/*
