name: CI
on:
  push:
    branches:
      - dev
      - main
      - ci
  pull_request:
    branches:
      - dev
      - main
  release:
    types: [published]

jobs:
  preload_containers:
    uses: ./.github/workflows/preload-containers.yml

  standard_test:
    needs: preload_containers
    uses: ./.github/workflows/standard-test.yml
    with:
      docker-cache-key: ${{ jobs.preload_containers.output.docker-cache-key }}
      singularity-cache-key: ${{ jobs.preload_containers.output.singularity-cache-key }}
    

