name: CI
on:
  push:
    branches:
      - dev
      - main
      - ci
  pull_request:
    branches:
      - dev
      - main
  release:
    types: [published]

jobs:
  preload_docker:
    uses: ./.github/workflows/preload-containers.yml
    with:
      docker: true

  preload_singularity:
    uses: ./.github/workflows/preload-containers.yml
    with:
      singularity: true   

  standard_test:
    needs: preload_docker
    uses: ./.github/workflows/standard-test.yml
    with:
      cache-key: ${{ needs.preload_docker.outputs.docker-cache-key }}
      docker: true
      singularity: false
      
    

