name: CI
on:
  push:
    branches:
      - dev
      - main
      - ci
  pull_request:
    branches:
      - dev
      - main
  release:
    types: [published]

jobs:
  preload_docker:
    uses: ./.github/workflows/preload-docker.yml

  preload_singularity:
    uses: ./.github/workflows/preload-singularity.yml

  standard_test_docker:        
    needs: preload_docker
    uses: ./.github/workflows/standard-test.yml
    with:
      cache-key: ${{ needs.preload_docker.outputs.cache-key }}
      docker: true

  standard_test_singularity:      
    needs: preload_singularity
    uses: ./.github/workflows/standard-test.yml
    with:
      cache-key: ${{ needs.preload_singularity.outputs.cache-key }}
      singularity: true

