name: CI
# This workflow runs the pipeline with the minimal test dataset to check that it
# completes without any syntax errors using docker, singularity, and conda
on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types: [published]

jobs:
  test:
    name: Run standard workflow test
    if: ${{ github.event_name == 'push'}}
    runs-on: ubuntu-latest
    env:
      NXF_VER: ${{ matrix.nxf_ver }}
      NXF_ANSI_LOG: false
      CAPSULE_LOG: none    
    strategy:
      fail-fast: false        
      matrix:
        test_profile: ["test", "test_json"]
        profile: ["docker", "singularity", "conda"]
        # Nextflow versions
        include:
          # Test pipeline minimum Nextflow version
          - NXF_VER: '21.04.0'
          # Test latest edge release of Nextflow
          - NXF_VER: ''
    concurrency: ${{ matrix.profile }}
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2
 
      - name: Set up Singularity
        if: matrix.profile == 'singularity'
        uses: eWaterCycle/setup-singularity@v5
        with:
          singularity-version: 3.7.1
          
      - name: Setup miniconda
        if: matrix.profile == 'conda'
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          auto-update-conda: true
          channels: conda-forge,bioconda,defaults
          python-version: ${{ matrix.python-version }}          

      - name: Conda clean
        if: matrix.profile == 'conda'
        run: conda clean -a

      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
        
      - name: Run pipeline with test data
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile ${{ matrix.test_profile}},${{ matrix.profile }}
