name: CI
on:
  push:
    branches:
      - dev
      - main
      - ci
  pull_request:
  release:
    types: [published]

env:
  SINGULARITY_VERSION: "3.8.3"

jobs:
  test:
    name: Run standard workflow test
    if: ${{ github.event_name == 'push'}}
    runs-on: ubuntu-latest
    env:
      NXF_VER: ${{ matrix.nxf_ver }}
      NXF_ANSI_LOG: false
      CAPSULE_LOG: none
    strategy:
      fail-fast: false
      matrix:
        test_profile: ["test"]
        profile: ["docker"]
        nxf_ver: ['22.10.0', ''] # minimum supported version, latest version
    concurrency: ${{ matrix.test_profile }}

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Make directory for docker images
        run: |
          mkdir -p ${{ runner.temp }}/docker/

      - name: Restore docker image cache
        id: cache-docker-restore
        if: matrix.profile == 'docker'
        uses: actions/cache/restore@v3
        with:
          path: ${{ runner.temp }}/docker/
          key: ${{ runner.os }}--${{ hashFiles('conf/modules.config') }}

      - name: Load docker images from cache
        if: matrix.profile == 'docker' && steps.cache-docker-restore.outputs.cache-hit == 'true'
        run: |
          find $HOME -name '*.tar'
          find ${{ runner.temp }}/docker/ -name '*.tar' -exec sh -c 'docker load < {}' \;

      - name: Run pipeline with test data on docker ${{ env.NXF_VER }} 
        if: matrix.profile == 'docker'
        continue-on-error: false
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile ${{ matrix.test_profile}},${{ matrix.profile }}

      - name: Save docker images
        if: matrix.profile == 'docker' && steps.cache-docker-restore.outputs.cache-hit != 'true'
        run: |
          # don't compress, because the cache action uses zstd
          docker images | awk -v OFS=':' 'NR > 1 { print $1,$2 }' | xargs -I {} sh -c 'docker save "$1" > ${{ runner.temp }}/docker/$(basename "$1").tar' - {}

      - name: Cache saved docker images
        id: cache-docker-pull
        uses: actions/cache/save@v3
        with:
          path: ${{ runner.temp }}/docker
          key: ${{ runner.os }}--${{ hashFiles('${{ runner.temp }}/docker') }}        


  unit_test:
    name: ${{ matrix.profile }} ${{ matrix.tags }}
    if: ${{ github.event_name == 'push'}}
    runs-on: ubuntu-latest
    env:
      NXF_ANSI_LOG: false
      CAPSULE_LOG: none
    strategy:
      fail-fast: false
      matrix:
        profile: ["docker", "singularity"]
        tags:
          - "pgscatalog test --pgs_id"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      - name: Cache singularity setup
        id: cache-singularity
        if: matrix.profile == 'singularity'
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/singularity/${{ env.SINGULARITY_VERSION }}/x64
          key: ${{ runner.os }}-singularity-${{ env.SINGULARITY_VERSION }}

      - name: Set up Singularity
        uses: eWaterCycle/setup-singularity@v7
        if: steps.cache-singularity.outputs.cache-hit != 'true' && matrix.profile == 'singularity'
        with:
          singularity-version: ${{ env.SINGULARITY_VERSION }}

      - name: Add singularity to path
        if: steps.cache-singularity.outputs.cache-hit == 'true' && matrix.profile == 'singularity'
        run: |
          echo "/opt/hostedtoolcache/singularity/${{ env.SINGULARITY_VERSION }}/x64/bin" >> $GITHUB_PATH

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r ${{ github.workspace }}/tests/requirements.txt

      - name: Cache nextflow setup
        id: cache-nextflow
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/nextflow
          key: ${{ runner.os }}-nextflow

      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Run unit tests
        run: TMPDIR=~ PROFILE=${{ matrix.profile }} pytest --kwdof --symlink --git-aware --wt 2 --tag "${{ matrix.tags }}" --ignore tests/bin

      - name: Output log on failure
        if: failure()
        run: |
          echo "======> log.out <======="
          cat /home/runner/pytest_workflow_*/*/log.out
          echo
          echo
          echo "======> log.err <======="
          cat /home/runner/pytest_workflow_*/*/log.err
      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: logs-${{ matrix.profile }}
          path: |
            /home/runner/pytest_workflow_*/*/.nextflow.log
            /home/runner/pytest_workflow_*/*/log.out
            /home/runner/pytest_workflow_*/*/log.err
            /home/runner/pytest_workflow_*/*/work
            !/home/runner/pytest_workflow_*/*/work/conda
            !/home/runner/pytest_workflow_*/*/work/singularity
