name: Run ancestry test with singularity or docker profiles

on:
  workflow_call:
    inputs:
      container-cache-key:
        type: string
        required: true
      correlation-cache-key:
        type: string
        required: true
      docker:
        type: boolean
      singularity:
        type: boolean

env:
  NXF_SINGULARITY_CACHEDIR: ${{ github.workspace }}/singularity
  SINGULARITY_VERSION: 3.8.3

jobs:
  docker:
    if: ${{ inputs.docker }}
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables
        run: |
          echo "CORRELATION_DIR=$RUNNER_TEMP" >> $GITHUB_ENV
      
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - uses: nf-core/setup-nextflow@v2

      - name: Restore docker images
        id: restore-docker
        uses: actions/cache/restore@v4
        with:
          path: ${{ runner.temp }}/docker
          key: ${{ inputs.container-cache-key }}
          fail-on-cache-miss: true

      - name: Load docker images from cache
        run: |
          find $HOME -name '*.tar'
          find ${{ runner.temp }}/docker/ -name '*.tar' -exec sh -c 'docker load < {}' \;

      - name: Restore reference data
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ env.CORRELATION_DIR }}/correlation37.pgen
            ${{ env.CORRELATION_DIR }}/correlation37.psam
            ${{ env.CORRELATION_DIR }}/correlation37.pvar.zst
          key: ${{ inputs.correlation-cache-key }}
          fail-on-cache-miss: true

      - name: Set up test requirements
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - run: pip install -r ${{ github.workspace }}/tests/requirements.txt

      - name: Run correlation test
        run: TMPDIR=~ PROFILE=docker pytest --kwdof --symlink --git-aware --wt 2 --tag "test score correlation"

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: logs-singularity-ancestry
          path: |
            /home/runner/pytest_workflow_*/*/.nextflow.log
            /home/runner/pytest_workflow_*/*/log.out
            /home/runner/pytest_workflow_*/*/log.err
            /home/runner/pytest_workflow_*/*/output/*
            
  singularity:
    if: ${{ inputs.singularity }}
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables
        run: |
          echo "CORRELATION_DIR=$RUNNER_TEMP" >> $GITHUB_ENV
      
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - uses: nf-core/setup-nextflow@v2

      - name: Restore singularity setup
        id: restore-singularity-setup
        uses: actions/cache@v4
        with:
          path: /opt/hostedtoolcache/singularity/${{ env.SINGULARITY_VERSION }}/x64
          key: ${{ runner.os }}-singularity-${{ env.SINGULARITY_VERSION }}
          fail-on-cache-miss: true

      - name: Add singularity to path
        run: |
          echo "/opt/hostedtoolcache/singularity/${{ env.SINGULARITY_VERSION }}/x64/bin" >> $GITHUB_PATH

      - name: Restore singularity container images
        id: restore-singularity
        uses: actions/cache@v4
        with:
          path: ${{ env.NXF_SINGULARITY_CACHEDIR }}
          key: ${{ inputs.container-cache-key }}

      - name: Restore reference data
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ env.CORRELATION_DIR }}/correlation37.pgen
            ${{ env.CORRELATION_DIR }}/correlation37.psam
            ${{ env.CORRELATION_DIR }}/correlation37.pvar.zst
          key: ${{ inputs.correlation-cache-key }}
          fail-on-cache-miss: true

      - name: Set up test requirements
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - run: pip install -r ${{ github.workspace }}/tests/requirements.txt

      - name: Run ancestry test
        run: TMPDIR=~ PROFILE=singularity pytest --kwdof --symlink --git-aware --wt 2 --tag "test score correlation"
        env:
          TMPDIR: ${{ runner.temp }}

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: logs-singularity-ancestry
          path: |
            /home/runner/pytest_workflow_*/*/.nextflow.log
            /home/runner/pytest_workflow_*/*/log.out
            /home/runner/pytest_workflow_*/*/log.err
            /home/runner/pytest_workflow_*/*/output/*
