name: Correlation test
on:
  push:
    branches:
      - correlation
      - ci
  workflow_dispatch:
  release:
    types: [published]

jobs:
  preload_correlation:
    uses: ./.github/workflows/preload-correlation.yml

  preload_docker:
    uses: ./.github/workflows/preload-docker.yml

  preload_singularity:
    uses: ./.github/workflows/preload-singularity.yml

  correlation_docker:
    needs: [preload_docker, preload_correlation]
    uses: ./.github/workflows/correlation.yml
    with:
      container-cache-key: ${{ needs.preload_docker.outputs.cache-key }}
      correlation-cache-key: ${{ needs.preload_correlation.outputs.cache-key }}
      docker: true

  correlation_singularity:
    needs: [preload_singularity, preload_correlation]
    uses: ./.github/workflows/correlation.yml
    with:
      container-cache-key: ${{ needs.preload_singularity.outputs.cache-key }}
      correlation-cache-key: ${{ needs.preload_correlation.outputs.cache-key }}
      singularity: true    
