name: Preload reference data

on:
  workflow_call:
    outputs:
      cache-key:
        value: ancestry
  
jobs:
  preload_reference:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "ANCESTRY_REF_DIR=$RUNNER_TEMP" >> $GITHUB_ENV
          echo "ANCESTRY_TARGET_DIR=$RUNNER_TEMP" >> $GITHUB_ENV

      - name: Cache reference data
        id: cache-ref
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.ANCESTRY_TARGET_DIR }}/GRCh38_HAPNEST_TARGET_ALL.pgen
            ${{ env.ANCESTRY_TARGET_DIR }}/GRCh38_HAPNEST_TARGET_ALL.psam
            ${{ env.ANCESTRY_TARGET_DIR }}/GRCh38_HAPNEST_TARGET_ALL.pvar.zst
            ${{ env.ANCESTRY_REF_DIR }}/GRCh38_HAPNEST_reference.tar.zst
          key: ancestry
          
      - name: Download reference data
        if: steps.cache-ref.outputs.cache-hit != 'true'        
        run: |
          wget -qnc -P $ANCESTRY_REF_DIR https://ftp.ebi.ac.uk/pub/databases/spot/pgs/resources/GRCh38_HAPNEST_reference.tar.zst
          wget -qnc -P $ANCESTRY_TARGET_DIR https://ftp.ebi.ac.uk/pub/databases/spot/pgs/resources/GRCh38_HAPNEST_target.tar.zst
          tar -xf $ANCESTRY_TARGET_DIR/GRCh38_HAPNEST_target.tar.zst -C $ANCESTRY_TARGET_DIR
          
