name: Preload singularity containers

on:
  workflow_call:
    outputs:
      cache-key:
        value: singularity-${{ github.sha }}

env:
  NXF_SINGULARITY_CACHEDIR: ${{ github.workspace }}/singularity
  SINGULARITY_VERSION: 3.8.3

jobs:
  singularity:
    runs-on: ubuntu-latest
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v4

      - name: Cache singularity setup
        id: cache-singularity-setup
        uses: actions/cache@v4
        with:
          path: /opt/hostedtoolcache/singularity/${{ env.SINGULARITY_VERSION }}/x64
          key: ${{ runner.os }}-singularity-${{ env.SINGULARITY_VERSION }}

      - name: Set up Singularity
        uses: eWaterCycle/setup-singularity@v7
        if: ${{ steps.cache-singularity-setup.outputs.cache-hit != 'true' }}
        with:
          singularity-version: ${{ env.SINGULARITY_VERSION }}

      - name: Add singularity to path
        if: steps.cache-singularity-setup.outputs.cache-hit == 'true'
        run: |
          echo "/opt/hostedtoolcache/singularity/${{ env.SINGULARITY_VERSION }}/x64/bin" >> $GITHUB_PATH

      - name: Pull and save singularity
        run: |
          mkdir -p $NXF_SINGULARITY_CACHEDIR
          git grep 'ext.singularity*' conf/modules.config | cut -f 2 -d '=' | xargs -L 2 echo | tr -d ' ' > ${{ runner.temp }}/singularity_images.txt
          cat ${{ runner.temp }}/singularity_images.txt | sed 's/oras:\/\///;s/https:\/\///;s/\//-/g;s/$/.img/;s/:/-/' > ${{ runner.temp }}/singularity_image_paths.txt
          paste -d '\n' ${{ runner.temp }}/singularity_image_paths.txt ${{ runner.temp }}/singularity_images.txt | xargs -L 2 sh -c 'singularity pull --disable-cache --dir $NXF_SINGULARITY_CACHEDIR $0 $1'

      - name: Cache singularity images
        id: cache-singularity-pull
        uses: actions/cache@v4
        with:
          path: ${{ env.NXF_SINGULARITY_CACHEDIR }}
          key: singularity-${{ github.sha }}
