name: Preload singularity and docker containers
description: Pulls and caches containers

on:
  workflow-call:
    outputs:
      docker-cache-key:
        description: "Docker cache key"
        value: ${{ runner.os }}-${{ github.sha }}
        
jobs:
  docker:
    runs-on: ubuntu-latest
    name: Save docker images

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      - name: Pull and save docker
        run: |
          git grep 'ext.docker*' ${{ github.workspace }}/conf/modules.config | cut -f 2 -d '=' | xargs -L 2 echo | tr -d ' ' > ${{ runner.temp }}/images.txt
          cat ${{ runner.temp }}/images.txt | xargs -I {} sh -c 'docker pull --platform linux/amd64 "$1"' - {}
          mkdir -p ${{ runner.temp }}/docker/
          cat ${{ runner.temp }}/images.txt | xargs -I {} sh -c 'docker save "$1" > ${{ runner.temp }}/docker/$(basename "$1").tar' - {}

      - name: Save docker
        id: cache-docker
        uses: actions/cache@v3
        with:
          path: ${{ runner.temp }}/docker
          key: ${{ runner.os }}-${{ github.sha }}
          
          
  
