name: Correlation test scores
on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types: [published]

jobs:
  score:
    name: Run correlation test
    if: ${{ github.event_name == 'push'}}
    runs-on: ubuntu-latest
    env:
      NXF_ANSI_LOG: false
      CAPSULE_LOG: none
    strategy:
      fail-fast: true
      matrix:
        profile: ["docker"]      
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      - name: Check out test dataset
        run: git clone https://gitlab.ebi.ac.uk/gdp-public/testdata.git          
        
