name: Run standard test with singularity and docker profiles

on:
  workflow_call:
    inputs:
      docker-cache-key:
        required: true
        type: string
      singularity-cache-key:
        required: true
        type: string

jobs:
  run_standard_docker:
    uses: ./.github/workflows/standard-test-docker.yml
    with:
      cache-key: ${{ inputs.docker-cache-key }}

  run_standard_singularity:
    uses: ./.github/workflows/standard-test-singularity.yml
    with:
      cache-key: ${{ inputs.singularity-cache-key }}
